### ISSUE TITLE
MPI Messages

### ISSUE THREAD

**Issue by LyndStringer** [NOAA-GSL/SENA-yppm#1]
I am seeing MPI messages in the log.out files.

MPI rank 0 thread 0 on hfe11. (Runnable range: lo=0 hi=0)
MPI rank 0 thread 3 on hfe11. (Runnable range: lo=3 hi=3)
MPI rank 0 thread 1 on hfe11. (Runnable range: lo=1 hi=1)

But I do not see kernel yppm using MPI, it appears to be serially coded.

**Comment by christopherwharrop-noaa** [comment]
@LyndStringer - Those messages are from the print_affinity() routine, which was written assuming that you have MPI+threading.  Those are not coming from MPI.  So, while perhaps we could update them to prevent some confusion, they are (otherwise) not harmful, and will help you look at affinity if you are using OpenMP.

**Comment by LyndStringer** [comment]
@christopherwharrop-noaa It certainly is confusing, since the messages do not come from MPI (as you pointed out) and there is only one thread.  I'm thinking to delete it or make the message correct and useful.

**Comment by christopherwharrop-noaa** [comment]
@LyndStringer - I think we should keep the code because it is useful for analyzing affinity issues whether MPI is used or not, and I definitely foresee it being used in the future. It could be modified, though, to detect whether MPI is in use or not, and print a more appropriate message.

**Comment by LyndStringer** [comment]
Fixed.

**Comment by christopherwharrop-noaa** [comment]
Fixed by #9
